oidc:
  client-id: secure-photo-hub-rest-api
  client-secret: ezMGqpvhRqwHyXp1g7BFPbqslcozacKH
aws-s3:
  endpoint-url: https://s3.localhost.localstack.cloud:4566
  access-key-id: test
  secret-access-key: test
  region: eu-west-1
  bucket-name: sample-bucket
database:
  username: user
  password: password