oidc:
  auth-server.url: http://localhost:8080/realms/fast-photo-hub
  scopes: openid profile email offline_access
  redirect-uri: http://localhost:8085/openid_redirect_uri_endpoint
redis:
  host: redis://127.0.0.1:6379